#!/bin/bash

if [ $# -lt 1 ]; then
	echo usage: $0 file_list
	exit -1
fi

if [ -f cscope.files ]; then
	rm cscope.files
fi

tag_files=$1
IFS=$'\n'
for line in `cat $tag_files`
do
	IFS=$' '
	find $line -name "*.[chS]" >> cscope.files
done

ctags -L cscope.files
cscope -bkq -f cscope.out
exit 0
